" x4m3's vimrc
" http://philippeloctaux.com
"

set tabstop=4 "how many columns is a tab
set shiftwidth=4 "how much to indent

set colorcolumn=80 "get a colored bar at char 80
set modeline "be able to run vim config at the end of files
set fileformat=unix "always save in unix format
set encoding=utf-8 "always use utf-8
set incsearch "highlight search result as you type it
set hlsearch "highlight all search results
filetype indent plugin on "enable identation & plugins for filetypes thing
syntax on "enable syntax color

"folders
set backupdir=~/.vim/backup/ "backup folder
set directory=~/.vim/swap/ "swap folder
set undodir=~/.vim/undo/ "undo folder

"macros and maps
map <F2> iPhilippe Loctaux <email><ESC><CR>
map <F3> iSigned-off-by: Philippe Loctaux <email><ESC><CR>
map <F4> :UndotreeToggle<CR>
map <F5> :Vaffle<CR>
map <F6> :Gcommit %<CR>
map <F7> :CarbonNowSh<CR>

"install vim-plug if it's not installed
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
				\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

"start plugging stuff
call plug#begin('~/.vim/plugged')
Plug 'https://git.x4m3.rocks/x4m3/vim-dhex' "hex editor
Plug 'https://git.x4m3.rocks/x4m3/vim-epitech' "epitech
Plug 'tpope/vim-fugitive' "git
Plug 'mbbill/undotree' "list of undos
Plug 'cocopon/vaffle.vim' "file manager
Plug 'vim-airline/vim-airline' "status bar
Plug 'sgur/vim-editorconfig' "editorconfig
Plug 'kristijanhusak/vim-carbon-now-sh' "screenshots
Plug 'iamcco/markdown-preview.vim' "markdown
Plug 'valloric/YouCompleteMe' "auto completion
Plug 'Raimondi/delimitMate' "auto completion for brackets, parentheses, etc
call plug#end()

"window navigation
"see :help key-notation
noremap <TAB> <C-W>w

"see tabs as characters
set list
set listchars=tab:>-

"no arrow keys!
"thx http://bondoer.fr
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

"use plain ascii for powerline
let g:airline_symbols_ascii=1
