" x4m3's vimrc
" http://philippeloctaux.com
"

set tabstop=4 "how many columns is a tab
set shiftwidth=4 "how much to indent

set colorcolumn=80 "get a colored bar at char 80
set modeline "be able to run vim config at the end of files
set fileformat=unix "always save in unix format
set encoding=utf-8 "always use utf-8
set incsearch "highlight search result as you type it
set hlsearch "highlight all search results
set showmatch "highlight matching () {} []
set backspace=indent,eol,start "iterm2 bullshit
set number relativenumber "relative line numbers
filetype indent plugin on "enable identation & plugins for filetypes thing
syntax on "enable syntax color

"folders
set backupdir=~/.vim/backup// "backup folder
set directory=~/.vim/swap// "swap folder
set undodir=~/.vim/undo// "undo folder

"macros and maps
map <F2> iPhilippe Loctaux <email><ESC><CR>
map <F3> iSigned-off-by: Philippe Loctaux <email><ESC><CR>
map <F4> :UndotreeToggle<CR>
map <F5> :Gcommit %<CR>
map <F6> :CarbonNowSh<CR>
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

"disable ex mode
map q: <Nop>
nnoremap Q <nop>

"install vim-plug if it's not installed
if empty(glob('~/.vim/autoload/plug.vim'))
	silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
				\ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

"start plugging stuff
call plug#begin('~/.vim/plugged')
Plug 'https://git.x4m3.rocks/x4m3/vim-dhex' "hex editor
Plug 'https://git.x4m3.rocks/x4m3/vim-epitech' "epitech
Plug 'tpope/vim-fugitive' "git
Plug 'mbbill/undotree' "list of undos
Plug 'itchyny/lightline.vim' "status bar
Plug 'sgur/vim-editorconfig' "editorconfig
Plug 'kristijanhusak/vim-carbon-now-sh' "screenshots
Plug 'gabrielelana/vim-markdown' "markdown syntax
Plug 'iamcco/markdown-preview.vim' "markdown preview
Plug 'Raimondi/delimitMate' "auto completion for brackets, parentheses, etc
Plug 'ctrlpvim/ctrlp.vim' "fuzzy finder
Plug 'airblade/vim-gitgutter' "git status in files
Plug 'morhetz/gruvbox' "colorscheme
Plug 'Yggdroot/indentLine' "show indentation
Plug 'rust-lang/rust.vim' "rust
Plug 'lifepillar/vim-mucomplete' "auto completion
Plug 'Rip-Rip/clang_complete' "c and c++ completion
call plug#end()

"colors and themes
set termguicolors
set background=dark
colorscheme gruvbox

"window navigation
"see :help key-notation
noremap <TAB> <C-W>w

"see tabs as characters
set list
set listchars=tab:>-

"statusline config
set timeoutlen=1000 ttimeoutlen=0 "chaning update time
set laststatus=2
set noshowmode

"gitgutter config
set updatetime=100

"indentline confg
let g:indentLine_setColors = 0

"mucomplete
let g:mucomplete#enable_auto_at_startup = 1
set noinfercase
set completeopt-=preview
set completeopt+=menuone,noinsert "for autocompletion
set shortmess+=c "shut off completion messages
set belloff+=ctrlg "if vim beeps during completion

"clang_complete
let g:clang_complete_auto = 1
let s:clang_library_path='/Library/Developer/CommandLineTools/usr/lib'
if isdirectory(s:clang_library_path)
	let g:clang_library_path=s:clang_library_path
elseif
	let s:clang_library_path='/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib'
	if isdirectory(s:clang_library_path)
		let g:clang_library_path=s:clang_library_path
	endif
else
	let s:clang_library_path = '/usr/lib64/'
	if isdirectory(s:clang_library_path)
		let g:clang_library_path=s:clang_library_path
	endif
endif
