# x4m3's zshrc
# echo cEBwaGlsaXBwZWxvY3RhdXguY29tCg== | base64 -d

# zsh and ohmyzsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/point/zsh/

# env
export LANG=en_US.UTF-8
export EDITOR="nvim"
export SSH_KEY_PATH="~/.ssh/id_rsa"
export GPG_TTY=$(tty)
export NAME="Philippe Loctaux"
export EMAIL="p@philippeloctaux.com"
