# x4m3's zshrc
# echo cEBwaGlsaXBwZWxvY3RhdXguY29tCg== | base64 -d

# zsh and ohmyzsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/point/zsh/

# alias
alias mydockerps='docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Status}}\t{{.CreatedAt}}\t{{.Ports}}"'
alias webserver='python3 -m http.server --directory $1'

# path
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.cargo/bin:$PATH"

# env
export LANG=en_US.UTF-8
export EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/id_rsa"
export GPG_TTY=$(tty)
export NAME="Philippe Loctaux"
export EMAIL="p@philippeloctaux.com"
