#!/bin/zsh
#
# echo cEBwaGlsaXBwZWxvY3RhdXguY29tCg== | base64 -d

export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/point/zsh/

export SSH_KEY_PATH="~/.ssh/id_rsa"
export PATH="$HOME/bin:$HOME/.local/bin:$HOME/.cargo/bin:$GEM_HOME/bin:$(ruby -e 'print Gem.user_dir')/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export GEM_HOME="$HOME/.gems"
export EDITOR='vim'
export LANG=en_US.UTF-8
export TERM=xterm-256color

# lolcommits config
export LOLCOMMITS_DEVICE=/dev/video0
export LOLCOMMITS_DIR="$HOME/yadisk/lolcommits"

DISABLE_UPDATE_PROMPT=true
ZSH_DISABLE_COMPFIX=true

ZSH_THEME="x4m3"

plugins=(
	git
)

# function to generate a password or a username
function gen() {
	if [ -z "$1" ]; then
		< /dev/urandom tr -dc A-Za-z0-9 | head -c 32; echo
		return 0;
	fi
	< /dev/urandom tr -dc A-Za-z0-9 | head -c $1; echo
}

alias of='offlineimap'
alias om='offlineimap && mutt'
alias ne='emacs -nw'
alias sl='ls'
alias vi='vim'
alias v='vim'
alias m='man'

source $ZSH/oh-my-zsh.sh
