# x4m3's zshrc
# echo cEBwaGlsaXBwZWxvY3RhdXguY29tCg== | base64 -d

DISABLE_UPDATE_PROMPT=true
ZSH_DISABLE_COMPFIX=true

ZSH_THEME="x4m3"

plugins=(
	git
)

# function to generate a password or a username
function gen() {
	if [ -z "$1" ]; then
		< /dev/urandom tr -dc A-Za-z0-9 | head -c 32; echo
		return 0;
	fi
	< /dev/urandom tr -dc A-Za-z0-9 | head -c $1; echo
}

source $ZSH/oh-my-zsh.sh
